export default [
  {
    owner: "stephanalas",
    repo: "2101_tasks",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 2,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "acme-groceries",
    username: "stephanalas",
    commitsToRepo: 1,
    totalCommits: 5,
    commitPercentage: 20,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "acme-movie-api",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 3,
    commitPercentage: 0,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "acme-people-places-things",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 3,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "acme_auth",
    username: "stephanalas",
    commitsToRepo: 1,
    totalCommits: 1,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "adventureVote",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 13,
    commitPercentage: 0,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "curvy_dominoes",
    username: "stephanalas",
    commitsToRepo: 14,
    totalCommits: 14,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "curvy_royale",
    username: "stephanalas",
    commitsToRepo: 10,
    totalCommits: 11,
    commitPercentage: 90.91,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "dominoes",
    username: "stephanalas",
    commitsToRepo: 31,
    totalCommits: 64,
    commitPercentage: 48.44,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "family-tree",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 4,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "github-actions",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 2,
    commitPercentage: 0,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "jpfp",
    username: "stephanalas",
    commitsToRepo: 59,
    totalCommits: 59,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "loops-foundations",
    username: "stephanalas",
    commitsToRepo: 1,
    totalCommits: 1,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "mock-ecommerce-shop",
    username: "stephanalas",
    commitsToRepo: 8,
    totalCommits: 8,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "money",
    username: "stephanalas",
    commitsToRepo: 4,
    totalCommits: 4,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "No-Cap",
    username: "stephanalas",
    commitsToRepo: 39,
    totalCommits: 369,
    commitPercentage: 10.57,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "node-shell",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 1,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "phaser3-typescript-project-template",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 6,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "pomodoro-go",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 695,
    commitPercentage: 0,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "promize",
    username: "stephanalas",
    commitsToRepo: 0,
    totalCommits: 9,
    commitPercentage: 0,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "python-cheatsheet",
    username: "stephanalas",
    commitsToRepo: 1,
    totalCommits: 2010,
    commitPercentage: 0.05,
    forked: true,
  },
  {
    owner: "stephanalas",
    repo: "salas-marketing-tool",
    username: "stephanalas",
    commitsToRepo: 91,
    totalCommits: 91,
    commitPercentage: 100,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "Tenderizer-Minigame",
    username: "stephanalas",
    commitsToRepo: 3,
    totalCommits: 36,
    commitPercentage: 8.33,
    forked: false,
  },
  {
    owner: "stephanalas",
    repo: "zspraggs-checkin",
    username: "stephanalas",
    commitsToRepo: 2,
    totalCommits: 2,
    commitPercentage: 100,
    forked: false,
  },
];
